name: Pull Request Review Notification

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    steps:
      - name: Slack Notification
        # pr is not ready for review
        if: github.event.pull_request.draft != true
        uses: rtCamp/action-slack-notify@v2
        with:
          slack_webhook: ${{ env.SLACK_WEBHOOK }}
          # channel: twip-next-fe-notify
          color: ${{ job.status }}
          username: twip-next-fe - Build
          icon_url: https://assets.mytwip.net/favicon/v2/apple-icon-57x57.png
          message: |
            *PR Review Requested*
            ${{ github.event.pull_request.html_url }}
            ${{ github.event.pull_request.title }}
            ${{ github.event.pull_request.user.login }}
            ${{ github.event.pull_request.body }}
