name: github push action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Report Status - Start
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.sha }}
          echo ${{ github.ref }}
          echo ${{ github.repository }}
          echo ${{ github.repository_owner }}
          echo ${{ github.actor }}
          echo ${{ github.workflow }}
          echo ${{ github.action }}
          echo ${{ github.action_path }}
          echo ${{ github.action_ref }}
          echo ${{ github.action_repository }}
          echo ${{ github.action_status }}
