name: github push action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Report Status - Start
        run: |
          echo ${{ github.workflow }}
          echo https://github.com/kor-sams-dev/github-action/actions/runs/${{ github.run_id }}
